name: Bug report
about: Report a bug in GodSVG
title: Title
labels: bug
assignees: ''

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a clear and concise description of what the bug is and what the expected behavior is. For non-trivial issues, provide reproduction steps and screenshots if relevant.
    validations:
      required: true
