name: Bug report
description: Report a bug in GodSVG
labels: ["bug"]
body:
  - type: textarea
    attributes:
      description: |
        Give a clear and concise description of what the bug is and what the expected behavior is.
        For non-trivial issues, provide reproduction steps, screenshots and video if relevant, and the platform you used GodSVG on.
    validations:
      required: true
