name: Feature request
description: Suggest a new feature for GodSVG
labels: ["proposal"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: |
        Describe your limitation and how the feature will help to resolve it. Make sure you're addressing the newest version of GodSVG.
        Give as much detail about the exact implementation as you can, to make it more actionable. Feel free to attach drawings, diagrams, examples from other software.
        Please keep your proposal focused on a single thing.
    validations:
      required: true
