name: Feature request
about: Suggest a new feature for GodSVG
title: Title
labels: proposal
assignees: ''

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the limitation you're facing and how the feature will help resolve it. If you can, give more detail about the implementation.
    validations:
      required: true
