name: Feature request
description: Suggest a new feature for GodSVG
labels: ["proposal"]
body:
  - type: textarea
    attributes:
      description: |
        Describe your limitation and how the feature will help to resolve it.
        If you can, give more detail about the implementation.
        Please limit your proposal to a single issue, not multiple.
