name: Setup Godot Build Context
description: Derives GODOT_FEATURE_VERSION, hashes build options and restores cache

outputs:
  hash:
    description: "sha1 of build parameters"
    value: ${{ steps.buildhash.outputs.hash }}
  cache_hit:
    description: "cache restore hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Derive GODOT_FEATURE_VERSION
      shell: bash
      run: echo "GODOT_FEATURE_VERSION=$(echo $GODOT_VERSION | cut -d. -f1,2)" >> $GITHUB_ENV

    - name: Hash the build parameters
      id: buildhash
      shell: bash
      run: |
        printf '%s' "$BUILD_OPTIONS" > /tmp/build_opts_and_disabled
        if [ -f godsvg/.github/disabled_classes.gdbuild ]; then
          printf '\n' >> /tmp/build_opts_and_disabled
          cat godsvg/.github/disabled_classes.gdbuild >> /tmp/build_opts_and_disabled
        fi
        if command -v sha1sum >/dev/null 2>&1; then
          sha1sum /tmp/build_opts_and_disabled | awk '{print $1}' > /tmp/build_hash
        else
          shasum -a 1 /tmp/build_opts_and_disabled | awk '{print $1}' > /tmp/build_hash
        fi
        echo "hash=$(cat /tmp/build_hash)" >> $GITHUB_OUTPUT

    - name: Cache Template
      id: cache
      uses: actions/cache@v3
      with:
        key: template-${{ env.PLATFORM }}-${{ env.GODOT_VERSION }}-${{ env.GODOT_RELEASE }}-${{ steps.buildhash.outputs.hash }}
        path: ${{ runner.os == 'macOS' && '/Users/runner/Library/Application Support/Godot/export_templates/' || '~/.local/share/godot/export_templates/' }}
