## A database for the colors that themes use in the project.
extends Node

var focus_color := Color("66ccff", 0.8)
var common_panel_inner_color := Color("191926")
var common_panel_border_color := Color("414159")
var common_caret_color := Color("def", 0.87)
var common_selection_color := Color("668cff", 0.4)
var common_text_color := Color("def")
var common_subtle_text_color := Color(Color.WHITE, 0.33)
var common_inner_color_disabled := Color("0e0e12")
var common_border_color_disabled := Color("1e1f24")
var common_separator_color := Color("414159", 0.6)

var common_button_inner_color_normal := Color("1c1e38")
var common_button_border_color_normal := Color("313859")
var common_button_inner_color_hover := Color("232840")
var common_button_border_color_hover := Color("43567a")
var common_button_inner_color_pressed := Color("3d5499")
var common_button_border_color_pressed := Color("608fbf")

var connected_button_inner_color_normal := Color("10101a")
var connected_button_border_color_normal := Color("272733")
var connected_button_inner_color_hover := Color("181826")
var connected_button_border_color_hover := Color("3a3a4d")
var connected_button_inner_color_pressed := Color("313559")
var connected_button_border_color_pressed := Color("54678c")

var icon_normal_color := Color("bfbfbf")
var context_icon_normal_color := Color("d9d9d9")
var icon_hover_color := Color.WHITE
var icon_pressed_color := Color("bfdfff")
var icon_toggled_off_color := Color("808080")
var icon_toggled_on_color := Color("def", 0.87)

var translucent_button_color_normal := Color("def", 0.07)
var translucent_button_color_hover := Color("def", 0.14)
var translucent_button_color_pressed := Color("def", 0.27)
var translucent_button_color_disabled := Color("05060755")
var flat_button_color_hover := Color("def", 0.07)
var flat_button_color_pressed := Color("def", 0.2)
var flat_button_color_disabled := Color("050607", 0.27)

var dark_panel_color := Color("11111a")
var overlay_panel_inner_color := Color("060614")
var overlay_panel_border_color := Color("344166")

var scrollbar_normal_color := Color("344166")
var scrollbar_hover_color := Color("465580")
var scrollbar_pressed_color := Color("608fbf")
var scrollbar_background_color := Color("0f0f1a", 0.6)

var line_edit_focus_color := Color("3d6b99")
var line_edit_background_color := Color("10101a")
var line_edit_normal_border_color := Color("272733")
var line_edit_hover_border_overlay_color := Color("ddeeff", 0.11)
var mini_line_edit_normal_border_color := Color("4d4e66")

var tab_container_panel_inner_color := Color("171726")
var tab_container_panel_border_color := Color("2a2e4d")
var tabbar_background_color := Color("13131f", 0.5)
var hovered_tab_color := Color("1f2138")
var normal_tab_color := Color("17192e")
var selected_tab_color := Color("293052")
var selected_tab_border_color := Color("608fbf")
