name: export-optimized

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 4.8
  GODOT_RELEASE_TYPE: dev6
  GODOT_COMMIT_HASH: 8898c2b3db32adf6f92c694ffb6dac19af672e5f
  EMSDK_VERSION: latest

#  GODOT_VERSION: 4.6
#  GODOT_RELEASE_TYPE: stable
#  GODOT_COMMIT_HASH: 89cea143987d564363e15d207438530651d943ac
#  EMSDK_VERSION: 4.0.11

jobs:
  build-web:
    name: Export GodSVG for Web
    runs-on: ubuntu-latest
    env:
      PLATFORM: "Web"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: godsvg

      - name: Set up Godot Editor
        run: |
          mkdir -p ~/godot-editor
          cd ~/godot-editor
          wget -q https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-${GODOT_RELEASE_TYPE}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE_TYPE}_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-${GODOT_RELEASE_TYPE}_linux.x86_64.zip
          mv ./Godot_v${GODOT_VERSION}-${GODOT_RELEASE_TYPE}_linux.x86_64 ~/godot-editor/godot
          echo "~/godot-editor" >> $GITHUB_PATH

      - name: Install dependencies
        run: sudo apt-get install -y scons python3

      - name: Clone Godot repository
        run: git clone https://github.com/godotengine/godot.git godot

      - name: Checkout specific commit
        run: |
          cd godot
          git fetch
          git checkout $GODOT_COMMIT_HASH

      - name: Set up Emscripten
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: ${{ env.EMSDK_VERSION }}

      - name: Build Godot template for Web
        run: |
          cd godot
          scons p=web arch=wasm32 target=template_release lto=full production=yes deprecated=no minizip=no d3d12=no vulkan=no use_volk=no disable_3d=yes disable_physics_2d=yes disable_navigation_2d=yes modules_enabled_by_default=no module_freetype_enabled=yes module_gdscript_enabled=yes module_svg_enabled=yes module_jpg_enabled=yes module_webp_enabled=yes module_dds_enabled=yes module_text_server_adv_enabled=yes graphite=no module_mbedtls_enabled=yes threads=no
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE_TYPE}/
          mv ./bin/godot.web.template_release.wasm32.nothreads.zip ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE_TYPE}/web_nothreads_release.zip

      - name: Export project
        run: |
          cd godsvg
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/Bloated.html
          cd build/web
          mv Bloated.html index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bloated.Web
          path: godsvg/build/web
