name: compare-godot-pck

on:
  pull_request:
    branches: [ main ]

env:
  GODOT_GOOD_VERSION: 4.6-stable
  GODOT_REGRESSED_VERSION: 4.6.1-stable

jobs:
  build-good:
    name: Good PCK export
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GodSVG
        uses: actions/checkout@v6
        with:
          path: godsvg

      - name: Set up Godot Editor
        run: |
          mkdir -p ~/godot-editor
          cd ~/godot-editor
          wget -q https://github.com/godotengine/godot-builds/releases/download/${GODOT_GOOD_VERSION}/Godot_v${GODOT_GOOD_VERSION}_linux.x86_64.zip
          unzip Godot_v${GODOT_GOOD_VERSION}_linux.x86_64.zip
          mv Godot_v${GODOT_GOOD_VERSION}_linux.x86_64 ~/godot-editor/godot
          echo "~/godot-editor" >> $GITHUB_PATH

      - name: Export project
        run: |
          cd godsvg
          mkdir -p build/web
          godot --headless --export-pack "Web" build/web/normal.pck

      - name: Upload PCK
        uses: actions/upload-artifact@v7
        with:
          name: godsvg-${{ env.GODOT_GOOD_VERSION }}-pck
          path: godsvg/build/web/normal.pck

  build-regressed:
    name: Regressed PCK export
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GodSVG
        uses: actions/checkout@v6
        with:
          path: godsvg

      - name: Set up Godot Editor
        run: |
          mkdir -p ~/godot-editor
          cd ~/godot-editor
          wget -q https://github.com/godotengine/godot-builds/releases/download/${GODOT_REGRESSED_VERSION}/Godot_v${GODOT_REGRESSED_VERSION}_linux.x86_64.zip
          unzip Godot_v${GODOT_REGRESSED_VERSION}_linux.x86_64.zip
          mv Godot_v${GODOT_REGRESSED_VERSION}_linux.x86_64 ~/godot-editor/godot
          echo "~/godot-editor" >> $GITHUB_PATH

      - name: Export project
        run: |
          cd godsvg
          mkdir -p build/web
          godot --headless --export-pack "Web" build/web/bloated.pck

      - name: Upload PCK
        uses: actions/upload-artifact@v7
        with:
          name: godsvg-${{ env.GODOT_REGRESSED_VERSION }}-pck
          path: godsvg/build/web/bloated.pck

