name: Static Checks
on: [pull_request]

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -yq --no-install-recommends dos2unix recode

    - name: File formatting checks (file_format.sh)
      run: bash ./.github/file_format.sh
