name: Static Checks
on: [pull_request]

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: File formatting checks (file_format.sh)
      run: bash ./.github/file_format.sh
