name: Static Checks
on: [pull_request]

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix recode

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: File formatting checks (file_format.sh)
        run: |
          if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            bash ./.github/file_format.sh ${{ steps.changed-files.outputs.all_changed_files }}
          else
            echo "No files changed"
          fi
